# Generated by Django 4.0.5 on 2022-06-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myawwards', '0009_auto_20191024_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
